import React from 'react';
import './../styles/characters.css';


const Itachi = ({toggleCharacter}) => {
    return ( 
        <div className="container">
            <button onClick={toggleCharacter}>VER HISTORIA DE MINATO</button>
            <h2 className="title">Itachi Uchiha</h2>
            <div className="container-history">
                <p className="history">Itachi nació dentro del Clan Uchiha, siendo el hijo mayor del líder del clan, Fugaku Uchiha y de su esposa Mikoto Uchiha. Él siempre fue considerado y elogiado como el mejor en su generación, un genio por encima de todos los demás. Incluso sobrepasaba las expectativas de un miembro experto del Clan Uchiha. Sin embargo, ni siquiera su familia, amigos o profesores lo podían entender. Cuando sólo tenía cuatro años, Itachi ya había sido testigo de la pérdida de muchas vidas debido a la Tercera Guerra Mundial Shinobi, que lo traumatizaron emocionalmente, al punto de considerar el suicidio, y lo hizo convertirse en un pacifista. A los 7 años, se graduó de la Academia Ninja como el primero en su clase después de sólo un año, por aquel entonces comenzó a sentir interés por el origen de la aldea, dominó el Sharingan a la edad de 8 años, pasó los exámenes Chūnin a los 10 años,[1][2][3][4] y se convirtió en capitán de las unidades ANBU a los 13 años. <br/><br/>
                Él fue muy elogiado por su padre, que veía el futuro de la familia en Itachi, por lo que descuidó a su hijo menor, Sasuke Uchiha. Sin embargo, durante este tiempo Itachi mostró gran afecto hacia su hermano pequeño, e incluso animó a su padre para ir a la ceremonia de Inscripción de Sasuke a la Academia, algo que su padre había olvidado diciendo que tenía una importante misión para establecer a Itachi en las filas ANBU. <br/><br/> 
                Cuando el Clan Uchiha comenzó a planear el golpe de estado para derrocar Konoha, Itachi, como ANBU, recibió el encargo de espiar a la aldea. Sabiendo que un golpe de Estado sólo conduciría a una nueva guerra ninja, Itachi comenzó a espiar a los Uchiha en su lugar, transmitiéndole información al Tercer Hokage y a los otros ancianos de Konoha. Durante este tiempo él comenzó a actuar de forma extraña con su clan, ya que no asistía a las reuniones del clan, hablaba en contra del ideal del clan y además fue considerado el principal sospechoso por la muerte de su mejor amigo, Shisui Uchiha, quien se había ahogado en el Río Nakano para proteger su Sharingan de Danzo. Debido a esto, el clan había perdido sus esperanzas en Itachi, y su padre comenzó a cambiar su enfoque a Sasuke en su lugar. Mientras tanto, los intentos del Tercer Hokage de negociar un final pacífico de las hostilidades entre las dos partes resultaron ineficaces; así, contra los deseos del Tercero, Danzo Shimura junto al Consejo de Konoha, le ordenó a Itachi exterminar a todo el Clan Uchiha. Itachi accedió con la única condición de que su hermano no fuera lastimado, justificando que deberá ser un Uchiha el que lo ajusticie en un futuro por el genocidio del Clan. <br/><br/>
                Antes de realizar su misión secreta, Itachi descubrió la existencia del supuesto Madara Uchiha, que estaba tratando de reavivar las llamas de la guerra de Konoha. Allí los dos hicieron un trato, en donde Itachi se ofrecía a masacrar al clan Uchiha a cambio de que el supuesto Madara no atacara de nuevo a Konoha. El ninja estuvo de acuerdo, Itachi y Madara (Tobi), mataron a su clan entero durante la noche, excepto a Sasuke. Por eso actuó como un villano, diciéndole a Sasuke que había matado a su familia sólo para poner a prueba sus habilidades. Antes de huir de la aldea como un traidor, incitó a su hermano a odiarlo y a que obtuviera más poder para que un día se vengara de él. <br/><br/>
                Sasuke intentó atacarlo por lo que despierta su Sharingan por primera vez, pero Itachi logró esquivar sus ataques. Cuando Itachi estaba recogiendo su banda ninja la cual se le había caído, él derrama lágrimas frente a su hermano. Luego procedió a incapacitar a Sasuke, quien despertó en el hospital recordando todo lo que quería que él hiciera. Desde ese momento Sasuke juro vengarse de él y poder restablecer la gloria del Clan Uchiha. Itachi dejó el pueblo como un traidor. Según Tobi, Itachi también tenía una novia, Izumi Uchiha, a quien mató durante la Masacre del Clan Uchiha. <br/><br/>
                Sabiendo que Konoha todavía querría eliminar a Sasuke, Itachi le pidió al Tercer Hokage mantenerlo a salvo. También amenazó a Danzo de no dañar a Sasuke o revelaría los secretos de Konoha a los países enemigos. Una vez que la seguridad de Sasuke estuvo asegurada, Itachi volvió a su plan original de llegar a ser famoso por su Masacre del Clan Uchiha. Itachi se unió a Akatsuki con el fin de mantener un ojo en la organización, junto con el supuesto Madara, en caso de que alguna vez actúe en contra de Konoha, mientras que esperaba su muerte a manos de Sasuke. Como un miembro de Akatsuki, Itachi se acercó a Orochimaru, en donde éste último intentó robar su cuerpo para obtener su Kekkei Genkai, el Sharingan. Itachi previendo sus intenciones, lo atrapó en un genjutsu con su Sharingan y le cortó la mano izquierda como castigo, obligando a Orochimaru a huir de la organización <br/><br/>
                Itachi se asoció con Kisame Hoshigaki, que en un principio recibió amenazas después de que éste trató de intimidarlo. Sin embargo, finalmente se convirtieron en buenos socios quienes compartían el vínculo común de haber traicionado a las personas más cercanas a ellos. En algún momento después de unirse a Akatsuki y que Orochimaru huyera, Itachi ayudó a reclutar a Deidara a la fuerza, en una batalla utilizando sólo genjutsu. Por esto, Deidara juró venganza contra Itachi, entrenando su ojo izquierdo para evitar volver a caer en un genjutsu de Itachi, y a su vez entrenó otros aspectos como jutsus para
                En algún momento, Itachi contrajo una enfermedad mortal. Se mantenía vivo a través de diversos medicamentos como el Kotarō y pura "fuerza de voluntad", con la esperanza de vivir lo suficiente para morir a manos de Sasuke. De esta enfermedad no se supo hasta que Tobi la mencionó pues en sus apariciones en la serie no mostró ningún síntoma, exceptuando en la pelea con Sasuke.</p>
            </div>
        </div>
     );
}
 
export default Itachi;