import React from 'react';
import './../styles/characters.css';


const Itachi = ({toggleCharacter}) => {
    return ( 
        <div className="container">
            <button onClick={toggleCharacter}>VER HISTORIA DE ITACHI</button>
            <h2 className="title">Minato Namikaze</h2>
            <div className="container-history">
                <p className="history"> Cuando era sólo un niño y estaba en la Academia Ninja, su compañera de clase Kushina Uzumaki pensaba que él era sólo un "Flacucho medio-afeminado". Él soñaba con ser reconocido por los aldeanos de Konoha al convertirse en hokage, pero Kushina consideraba que era un sueño imposible. Más tarde, cuando Kushina fue secuestrada por un grupo de ninjas de Kumogakure, ella dejó hilos de su cabello con la esperanza de que alguien la encontrara. Minato fue el único ninja de Konoha en demostrar ser lo suficientemente listo para entender la pista y fue capaz de rescatarla. Minato le había dicho que él siempre había admirado su cabello. En ese momento, ella ya no lo veía como un "Flacucho medio-afeminado", se había enamorado de él. <br/><br/>
                Según quienes lo conocían, Minato era un ninja con mucho talento, al haber sido considerado un genio que aparece sólo una vez por generación. Se graduó en la Academia Ninja a la edad de diez años y fue introducido en un equipo de Genin bajo la tutela de Jiraiya. Éste tuvo un interés especial en Minato y lo aceptó como aprendiz, le enseñó La Técnica de Invocación. En algún momento, Jiraiya le contó a Minato la profecía del Gran Sapo Sabio, creyendo que Minato podría ser el Niño de la Profecía. <br/><br/>
                En años posteriores, Minato fue puesto a cargo de un equipo Genin formado por Kakashi Hatake, Rin Nohara y Obito Uchiha. Durante la Tercera Guerra Mundial Shinobi, Minato llevó a su equipo en una misión en Kusagakure. Debido a que Kakashi recientemente fue promovido a Jōnin, Minato le dio el liderazgo de la misión a Kakashi mientras él iba a ayudar a las fuerzas de Konoha. Antes de irse, le dio a Kakashi un kunai especial como regalo de felicitación, equipado con el sello utilizado para su Jutsu Volador del Dios Trueno. <br/><br/>
                Mientras ayudaba a sus compañeros shinobis de Konoha, usó el Jutsu Volador del Dios Trueno para destruir toda la oposición de Iwagakure en un instante. Volvió a tiempo para salvar a Kakashi y a Rin de otro grupo de enemigos, pero no pudo salvar a Obito, quien después de haber sido herido de muerte al ser aplastado por una gran roca, le otorgó su Sharingan a Kakashi como regalo por haber sido ascendido a rango Jōnin. Cuando Kakashi se recuperó de la dura prueba, Minato les ayudó a completar la tarea de destruir el Puente Kannabi.  <br/><br/>
                En algún momento de la historia durante la Tercera Guerra Mundial Shinobi, Minato tiene una batalla con A, acompañado de Killer B. En lo que fue aparentemente el primer encuentro, Minato, un Inuzuka, un Akimichi y un cuarto miembro, se enfrentaron a A y su equipo. Allí, Minato y A tuvieron un choque de velocidad, Minato casi hiere gravemente al futuro Raikage antes de que B interceptara el ataque. Al recibir la señal de Konoha de retirada por el momento, Minato se quedó a alabar la valentía de Killer B y le dijo a A que tenía una buena familia y seguidores que lo rodean por lo que hizo, y también ofreció un consejo: el de asegurarse de que su hermano supiera quién era antes de convertirse ni en humano ni en Jinchūriki. Minato declaró entonces que la próxima vez que se encontraran, él estaría con el título de "Kage" en el momento, sin la intención de permitir que su enemigo escapara tan fácilmente. A intentó atacar a Minato antes de irse, creyendo que este se tele-transportaría a uno de sus kunai especiales, sin embargo, A se sorprendió al ver que el ninja de Konoha, apareció detrás de su hermano antes de darse cuenta de que Minato le había marcado antes. Impresionado por el hecho de que B hubiera deducido la táctica de Minato y puso a éste en una situación no favorable, ya que B tenia su espada apuntando hacia atrás donde aparecería él, Minato alabó a B por sus habilidades como shinobi y no por ser un Jinchūriki. <br/><br/>
                Poco después de la Tercera Guerra Mundial Shinobi, Minato fue electo como el Cuarto Hokage debido a que el Tercer Hokage decidió renunciar, asumiendo de esa manera las muertes y pérdidas ocasionadas durante la guerra antes mencionada. En el anime, poco después de la ceremonia celebrada, Minato envió a Kakashi a una misión consistente en ir a recibir un documento importante relacionado con el tratado de paz entre Konoha e Iwagakure. Sabiendo que Kakashi todavía se encontraba traumatizado por la muerte de Rin, Minato envió a Might Guy y a un grupo de ANBU como respaldo por si un incidente ocurría, demostrándose más adelante que esto fue una movida inteligente, ya que Kakashi fue atacado en el camino por varios shinobis, pero fue incapaz de defenderse por su trauma, además de que sufrió hiperventilación durante la batalla. Más tarde, Minato visitó a Kakashi en el hospital y decidió promoverlo a ANBU con la intención de que trabajara directamente bajo su tutela y pudiese tenerlo supervisado. Posteriormente, en algún momento durante su periodo como Hokage, Minato les enseñó el Jutsu del Dios Trueno Volador a sus guardias para facilitarles las tareas que él les encomendaba. <br/><br/>
                Más tarde, Kushina quedaría embarazada y, luego de leer el libro de Jiraiya, donde el personaje principal se llamaba "Naruto", Minato dijo que el protagonista era igual que Jiraiya. Fue entonces cuando Minato reveló que él y Kushina querían que su hijo fuera un shinobi como el del libro, y por eso decidieron ponerle el nombre de Naruto. Minato señaló que Jiraiya seria el padrino de Naruto y éste le preguntó si estaba seguro de que querría eso. Minato dijo que Jiraiya era un buen ejemplo para todos ellos y que no podía pensar en un shinobi mejor que él. <br/><br/>
                El día en que Naruto iba a nacer, Hiruzen preparó un lugar secreto fuera de la aldea para que se hiciera allí el parto. En el parto el sello que mantenía al Kyūbi dentro de Kushina se debilitaría, así que él estaría allí para evitar que el zorro escapase. Durante el parto le pregunta a Biwako si Kushina se encuentra bien, ya que nunca había sentido tanto dolor y ésta le dice que no entre en pánico, ésa es la razón por la que una mujer tiene hijos: los hombres no pueden soportar el dolor. <br/><br/>
                Inmediatamente después del parto, un hombre enmascarado conocido como "Tobi" irrumpe en el cuarto matando a Biwako y a Taji, tomando al recién nacido como rehén. El enmascarado amenaza al Hokage con matar a su hijo si él no se alejaba de Kushina y cuando está a punto de clavarle un Kunai, Minato rápidamente lo salva, pero se da cuenta que la sábana que cubría al bebé está llena de Sellos Explosivos, así que la tira y escapa usando su técnica de tele-transportación, llevando a Naruto a un lugar seguro. Mientras tanto, el extraño extrae al Kyūbi de Kushina y lo manipula con su Sharingan, haciendo que ataque la aldea. Minato vuelve por Kushina y la lleva junto a Naruto, luego se pone su túnica de Hokage y se prepara para pelear. <br/><br/>
                Minato se dirige a la Roca Hokage para evitar el ataque del Kyūbi, el cual fue invocado en medio de la aldea por el enmascarado. Después de haber desviado la Bola Bestia con Cola con su jutsu espacio-tiempo, Tobi aparece detrás de él, intentando llevárselo con una técnica similar a la del Cuarto Hokage, aunque éste último consigue escapar al bosque, siendo seguido por Tobi. Entonces, Minato empieza a pelear contra el enemigo, dejando en las manos de Hiruzen al Kyūbi, hasta que Minato logra colocar un sello contrato en el Uchiha, haciendo que perdiera el control sobre Kyūbi, causando que se retirara. A continuación, éste se dirige a las afueras de Konoha donde todos los ninjas de la aldea intentaban detener al Bijū, pero la bestia es inmovilizada por la invocación de Minato, Gamabunta, para detener el ataque del zorro y llevarla a otro lugar. La lucha prosiguió en el lugar donde se encontraba Kushina y Naruto, en donde su esposa intentaba devolver al zorro de nuevo a su cuerpo con lo último de su chakra para poder morir junto con él. <br/><br/>
                Minato, al ver la decisión de su esposa, se pone en un principio triste, pero después decide utilizar el Sello Consumidor del Demonio de la Muerte para encerrar la mitad del poder de la bestia en el cuerpo de Naruto, mientras que la otra mitad la sellaría en sí mismo a costo de su propia muerte. Así pues, cuando éste llama al demonio, la mano de la Parca sale de su cuerpo tomando parte del chakra del zorro y encerrándolo dentro de su cuerpo, causando que la bestia disminuyera de tamaño. Después de eso, él invoca un trono de ceremonia, donde coloca a su hijo para poder sellar la otra parte del poder de la bestia. En ese momento, el Bijū al ver lo que trataba de hacer, atacó rápidamente al niño, pero fue detenido por los padres, dejándose estos atravesar por sus garras, evitando que el niño fuera asesinado. Antes de empezar el proceso de sellado, el Cuarto Hokage invoca a Gerotora para poder escribir la llave del sello, y dárselo a su maestro Jiraiya. Al final, el Zorro Demonio de Nueve Colas es encerrado dentro de Naruto junto con el poco chakra de Kushina y Minato (con la idea de que estos se activaran más a delante), causando la muerte de ambos[8]. </p>
            </div>
        </div>
     );
}
 
export default Itachi;